### ISSUE TITLE
CBSA.JCL.INSTALL(RACF001) Bad JOB Card

### ISSUE THREAD

**Issue by EnsonoStevenPerva** [cicsdev/cics-banking-sample-application-cbsa#10]
Please move the JOB card to the front of the RACF001 job. This should prevent any `IKJ56700A ENTER JOBNAME CHARACTER(S)` messages from appearing when a user attempts to submit this job.

**Comment by JAMOGRAD** [comment]
Will do! Thank you for raising!

**Comment by JAMOGRAD** [comment]
This was an issue in a number of the JCL files. In some of them, the JOB card is later but is commented out, but in others I moved the JOB card to the top, instead of the copyright statement. This will be in the next commit.

**Comment by JAMOGRAD** [comment]
This has now been fixed, I believe.
