### ISSUE TITLE
CBSA.JCL.INSTALL(HBANKCSD) Documentation is Unclear

### ISSUE THREAD

**Issue by EnsonoStevenPerva** [cicsdev/cics-banking-sample-application-cbsa#11]
HBANKCSD has a docbox at the top of the job that is unclear with respect to symbol replacement. There are 3 separate instructions to change the symbol `@CICS_PREFIX@`. I believe the intent is to have three symbols:
`@CICS_PREFIX@` - The location of the CICS System Datasets
`@CSD_PREFIX@` - The location of the target region CSD
`@CBSA_PREFIX@` - The location of the CBSA install datasets

In its current state, a single replacement will not result in a successful job.

**Comment by JAMOGRAD** [comment]
Yes, that's a fair point. That bit of JCL has gone through several iterations and has gone a little wrong. I shall have a look.

You've got the right idea though. that's what they were meant to be.

**Comment by JAMOGRAD** [comment]
This has now been fixed, I believe.
