### ISSUE TITLE
Job CBSA.JCL.INSTALL(BANKDATA) step BANKDAT5 abends with S213

### ISSUE THREAD

**Issue by bill-keller** [cicsdev/cics-banking-sample-application-cbsa#12]
Job CBSA.JCL.INSTALL(BANKDATA) step BANKDAT5 abends with ABEND=S213 U0000 REASON=000000E9 due to extra space after @DB2_HLQ@ in line 97.

//         DD DISP=SHR,DSN=@DB2_HLQ@ .SDSNLOAD

**Comment by JAMOGRAD** [comment]
Thanks for spotting that! That will be fixed in the next version.

**Comment by JAMOGRAD** [comment]
This has now been fixed, I believe.
