### ISSUE TITLE
workload generator

### ISSUE THREAD

**Issue by GerMFHub** [cicsdev/cics-banking-sample-application-cbsa#13]
Hi,

is it possible to get a code that generates workload for CBSA app?

**Comment by PhilWakelin** [comment]
@GerMFHub are you looking for details of the REST API in order to drive your own HTTP workload to CBSA?

**Comment by GerMFHub** [comment]
@PhilWakelin I am looking for workload simulation process for CBSA app.  What I need is process to kickoff multiple transactions on CBSA app infrastructure, and keep that constant workload running for minutes, hours, days. Something similar that was done for GenApp

**Comment by PhilWakelin** [comment]
> @PhilWakelin I am looking for workload simulation process for CBSA app. What I need is process to kickoff multiple transactions on CBSA app infrastructure, and keep that constant workload running for minutes, hours, days. Something similar that was done for GenApp

@GerMFHub can you clarify how you want to drive the app, as CBSA has both 3270 and RESTful interfaces. I've asked the team to see if they can provide documentation on the REST interfaces, would that allow you to run a workload simulation?

**Comment by GerMFHub** [comment]
@PhilWakelin If you can provide it as REST service, that would be enough.

**Comment by PhilWakelin** [comment]
> @PhilWakelin If you can provide it as REST service, that would be enough.

@JAMOGRAD do we have details of the REST services we can make available?

**Comment by JAMOGRAD** [comment]
The RESTful interface to CBSA is now documented and can be found here:

https://github.com/cicsdev/cics-banking-sample-application-cbsa/blob/main/etc/usage/carbonReactUI/doc/CBSA_RESTful_Interface_Reference.md

@GerMFHub hope this is OK!
