### ISSUE TITLE
COMPALL job fails with return code 12. Copybooks missing

### ISSUE THREAD

**Issue by JAMOGRAD** [cicsdev/cics-banking-sample-application-cbsa#6]
The JCL COMPALL will compile the COBOL source and assemble the BMS maps required to run CICS Banking Sample Application.

Some of the COBOL compiles will fail with return code 12 and errors such as

`IGYLI0048-S   The member "BNK1CAM" was not found in the "COPY" library.`

This is because the missing members are created by BMS map generation which happens later in the job.

Workaround:

Resubmit the job. The BMS maps will have been assembled and the copybooks created, so the second run will succeed.

Fix:

Reorder the JCL so that the BMS maps are assembled first, followed by the COBOL compiles.

**Comment by EnsonoStevenPerva** [comment]
If you move any of the steps executing MAPGEN to the front of the job, this should fix this issue.

**Comment by JAMOGRAD** [comment]
This has now been fixed, I believe.
