### ISSUE TITLE
Installation Dataset Allocation Screenshot could be clearer

### ISSUE THREAD

**Issue by bradroeger** [cicsdev/cics-banking-sample-application-cbsa#9]
Thinking that the screenshot at [https://github.com/cicsdev/cics-banking-sample-application-cbsa/blob/main/etc/install/base/doc/CBSA_base_cobol_installation_instructions.md#in[…]ons](https://github.com/cicsdev/cics-banking-sample-application-cbsa/blob/main/etc/install/base/doc/CBSA_base_cobol_installation_instructions.md#installation-instructions) could maybe be updated with the allocate dataset screenshot? Looks like the one that's in the doc is after the dataset is created?

![image](https://github.com/cicsdev/cics-banking-sample-application-cbsa/assets/10367274/7f37cd42-4cc5-433f-85fc-74b377e86c3f)

**Comment by JAMOGRAD** [comment]
Good idea.

**Comment by JAMOGRAD** [comment]
Replaced (but I can't see what it looks like in the page yet).

**Comment by JAMOGRAD** [comment]
This has now been fixed, I believe.
